version: '3.8'
services:
  db:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'

  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

volumes:
  postgres_data:
